apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    app: postgres
spec:
  ports: 
    - name: postgres
      # puerto interno
      port: 5432
      # exponer el puerto
      nodePort: 30432
  type: NodePort # LoadBalancer: es para diferentes pods
  selector: 
    app: postgres