apiVersion: apps/v1
kind: Deployment
metadata: 
  name: postgres-deployment
  labels:
    app: postgres
spec:
  # Numero de replicas de los pods
  replicas: 1
  # Definir como la implementacion identifica los pods que puede administrar
  selector: 
    matchLabels:
      app: postgres
  # Plantilla de la indentificacion del pod
  template:
    metadata: 
      labels: 
        app: postgres
    # Definicion del contenedor
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          imagePullPolicy: IfNotPresent
          # Abrir los puertos de donde se envia y recibe el trafico del contenedor
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef: 
                name: postgres-secret
          # Punto de montaje e incializacion del contenedor
          volumeMounts:
            # Ruta por defecto de postgres (ciclo de vide independiente)
            - mountPath: /var/lib/postgresql/data
              name: postgresdb
            - mountPath: /docker-entrypoint-initdb.d
              name: init-script

      volumes:
        # Almacenar los datos db
        - name: postgresdb
          persistentVolumeClaim: 
            claimName: postgres-claim
        - name: init-script
          configMap:
            name: postgres-init-script-configmap