# Crear un reclamador que hace la peticion en una aplicacion
# para verificar cuanto alamcenamiento puede utiliar
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-claim
  labels: 
    app: postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests: 
      storage: 2Gi

