apiVersion: v1
kind: Secret #Tipo de archivo (fichero)
metadata: #Informacion del fichero
  name: postgres-secret
  labels:
    app: postgres
type: Opaque # Indicar que valores se van a proporcionar (variables de entorno)
data:
  POSTGRES_DB: cG9zdGdyZXM= #postgres
  POSTGRES_USER: cG9zdGdyZXM= #postgres
  POSTGRES_PASSWORD: cXdlcnR5