apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    app: postgres
spec:
  clusterIP: 10.96.1.2
  ipFamilies:
    - IPv4
  ports: 
    - name: postgres
      # puerto interno
      port: 5432
      # exponer el puerto
      nodePort: 30432
  type: NodePort # LoadBalancer: es para diferentes pods
  selector: 
    app: postgres